baseURL: "https://www.specialcase.dev/"
languageCode: "en-us"
title: Special Case by James Kerr
author: James Kerr
theme: blank
googleAnalytics: G-D8JVDHTGVB

params:
  description: The Personal Blog of James Kerr
  tagline: The Personal Blog
  author: James Kerr
  twitter: specialCaseDev
  images:
    - /img/site-thumbnail-image.jpg

markup:
  highlight:
    style: github
