baseURL: "https://www.jameskerr.blog/"
languageCode: "en-us"
title: James Kerr
author: James Kerr
theme: blank
googleAnalytics: G-D8JVDHTGVB
disqusShortname: jameskerrblog

params:
  author: James Kerr
  twitter: specialCaseDev
  images:
    - /img/site-thumbnail-image.jpg

markup:
  highlight:
    style: github

menus:
  main:
    - name: Twitter
      url: https://twitter.com/specialCaseDev
    - name: GitHub
      url: https://github.com/jameskerr
    - name: RSS
      url: /index.xml
    
